server:
  port: 3030

spring:
  application:
    name: study-spring-api-marvel
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/STUDY_API_MARVEL
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show_sql: true
      use_sql_comments: true
      ddl-auto: update

management:
  security:
    enabled: false
